```yaml
services:
  # Dashboard (Streamlit)
  - type: web
    name: portfolio-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  # Webhook API (FastAPI)
  - type: web
    name: portfolio-webhook
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:fastapi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: WEBHOOK_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
```

**How to use**

1. In Render → **Blueprints**, click **+ New** → **Blueprint** and paste this YAML.
2. After deploy, open each service → **Environment** and fill the variables.
3. Set `WEBHOOK_TOKEN` on the webhook service, then point TradingView to: `https://<portfolio-webhook>.onrender.com/webhook/tradingview?token=<WEBHOOK_TOKEN>`
